

# Define the input sequences, respective metadata, and reference sequence
inputs:
  s: 
    sequences: "data/S_segment_LASV_fasta_041423.fasta"
    metadata: "data/metadata_patch.tsv"
    reference_name: "Josiah_NC_004296_reverse_complement_2018-08-13"
    reference_annotation: "data/LASV_S_reference_NC_004296_patch.gff"

# Define the polyclonal data to make predictions
polyclonal_serum_models:
  121F:
    dms_wt_seq_id: "Josiah_NC_004296_reverse_complement_2018-08-13"
    mut_effects_df: "../data/lassa/filtered-polyclonal-data/121F_avg.csv"
    activity_wt_df: "../data/lassa/filtered-polyclonal-data/121F_epitope.csv"
    mut_effect_col: "escape_median"
    mutation_col: "mutation"
    icxx: 0.9
  2510C:
    dms_wt_seq_id: "Josiah_NC_004296_reverse_complement_2018-08-13"
    mut_effects_df: "../data/lassa/filtered-polyclonal-data/2510C_avg.csv"
    activity_wt_df: "../data/lassa/filtered-polyclonal-data/2510C_epitope.csv"
    mut_effect_col: "escape_median"
    mutation_col: "mutation"
    icxx: 0.9
  256A:
    dms_wt_seq_id: "Josiah_NC_004296_reverse_complement_2018-08-13"
    mut_effects_df: "../data/lassa/filtered-polyclonal-data/256A_avg.csv"
    activity_wt_df: "../data/lassa/filtered-polyclonal-data/256A_epitope.csv"
    mut_effect_col: "escape_median"
    mutation_col: "mutation"
    icxx: 0.9
  372D:
    dms_wt_seq_id: "Josiah_NC_004296_reverse_complement_2018-08-13"
    mut_effects_df: "../data/lassa/filtered-polyclonal-data/372D_avg.csv"
    activity_wt_df: "../data/lassa/filtered-polyclonal-data/372D_epitope.csv"
    mut_effect_col: "escape_median"
    mutation_col: "mutation"
    icxx: 0.9
  377H:
    dms_wt_seq_id: "Josiah_NC_004296_reverse_complement_2018-08-13"
    mut_effects_df: "../data/lassa/filtered-polyclonal-data/377H_avg.csv"
    activity_wt_df: "../data/lassa/filtered-polyclonal-data/377H_epitope.csv"
    mut_effect_col: "escape_median"
    mutation_col: "mutation"
    icxx: 0.9
  89F:
    dms_wt_seq_id: "Josiah_NC_004296_reverse_complement_2018-08-13"
    mut_effects_df: "../data/lassa/filtered-polyclonal-data/89F_avg.csv"
    activity_wt_df: "../data/lassa/filtered-polyclonal-data/89F_epitope.csv"
    mut_effect_col: "escape_median"
    mutation_col: "mutation"
    icxx: 0.9

