
# Define the input sequences, respective metadata, and reference sequence
# all paths should be relative to the root of the repository
inputs:
  s: 
    sequences: "my_profiles/LASV_Josiah_GP_DMS/non-pipeline_analyses/LASV_phylogeny_analysis/Results/LASV_S_segment_nucleotide.fasta"
    # the metadata file is a patch to the metadata file in the LASV_Josiah repo metadata, replacing "MISSING" with "?" for augur.
    metadata: "config/LASV_S_segment_metadata_patch.tsv"
    reference_name: "Josiah_NC_004296_reverse_complement_2018-08-13"
    reference_annotation: "config/LASV_S_reference_NC_004296_patch.gff"

# DMSA phenotype prediction
# dictionary of phenotype collections
# each collection has a name and a set of parameters
# For a number of individual experiemnts.
dmsa_phenotype_collections:
  all-sera:
    # directory containing escape csv's
    mut_effects_dir: "my_profiles/LASV_Josiah_GP_DMS/results/filtered_antibody_escape_CSVs"
    # name of the column containing the effect score
    mut_effect_col: "escape_median"
    # name of the column containing the mutation
    mutation_col: "mutation"
